import mongoose from "mongoose";
import { CATEGORY, SUB_CATEGORY } from "../utils/constants.js";

const ProductModel = new mongoose.Schema(
  {
    addedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    reviews: {
      type: [
        {
          type: mongoose.Schema.Types.ObjectId,
          ref: "Review",
        },
      ],
      default: undefined,
    },
    category: { type: String, enum: Object.values(CATEGORY) },
    subcategory: { type: String, enum: Object.values(SUB_CATEGORY) },
    images: {
      type: [
        {
          url: String,
          publicId: String,
        },
      ],
      default: undefined,
    },
    name: String,
    price: Number,
    origPrice: Number,
    discount: Number,
    style: String,
    switches: String,
    backlit: String,
    tenkeyless: Boolean,
    connection_type: String,
    color: String,
    socket: String,
    form_factor: Number,
    max_memory: Number,
    memory_slots: Number,
    core_count: Number,
    core_clock: Number,
    boost_clock: Number,
    tdp: Number,
    graphics: String,
    smt: Boolean,
    bd: Number,
    dvd: Number,
    cd: Number,
    bd_write: String,
    dvd_write: String,
    cd_write: String,
    type: String,
    capacity: Number,
    price_per_gb: Number,
    cache: Number,
    interface: String,
    chipset: String,
    memory: Number,
    length: Number,
    screen_size: Number,
    resolution: { type: [Number], default: undefined },
    refresh_rate: Number,
    response_time: Number,
    panel_type: String,
    aspect_ratio: String,
    speed: { type: [Number], default: undefined },
    modules: { type: [Number], default: undefined },
    first_word_latency: Number,
    cas_latency: Number,
    mode: Number,
    channels: Number,
    channel_wattage: Number,
    pwm: Boolean,
    psu: Number,
    side_panel: String,
    external_volume: Number,
    internal_35_bays: Number,
    tracking_method: String,
    max_dpi: Number,
    hand_orientation: String,
    capacity_w: Number,
    capacity_va: Number,
    resolutions: { type: [String], default: undefined },
    connection: String,
    focus_type: String,
    os: { type: [String], default: undefined },
    fov: Number,
    protocol: String,
    frequency_response: { type: [Number], default: undefined },
    microphone: Boolean,
    wireless: Boolean,
    enclosure_type: String,
    configuration: Number,
    wattage: Number,
    size: Number,
    rpm: { type: [Number], default: undefined },
    airflow: { type: [Number], default: undefined },
    noise_level: { type: [Number], default: undefined },
  },
  { timestamps: true }
);

export default mongoose.model("Product", ProductModel);
