export const ROLES = ["admin", "user"];

export const GENERAL = {
  VIDEO_CARDS: "Video Cards",
  CPUS: "CPUs",
  CPU_COOLERS: "CPU Coolers",
  OPTICAL_DRIVES: "Optical Drives",
  MEMORY: "Memory",
  MONITORS: "Monitors",
  INTERNAL_STORAGE: "Storage",
  CASES: "Cases",
  MOTHERBOARDS: "Motherboards",
  OPERATING_SYSTEMS: "Operating Systems",
  EXTERNAL_STORAGE: "External Storage",
  POWER_SUPPLIES: "Power Supplies",
};

export const PERIPHERALS = {
  SPEAKERS: "Speakers",
  HEADPHONES: "Headphones",
  MICE: "Mice",
  WEBCAMS: "Webcams",
  KEYBOARDS: "Keyboards",
};

export const ACCESSORIES_OTHER = {
  FAN_CONTROLLERS: "Fan Controllers",
  CASE_ACCESSORIES: "Case Accessories",
  CASE_FANS: "Case Fans",
  THERMAL_COMPOUND: "Thermal Compound",
  UPS_SYSTEMS: "UPS Systems",
};

export const EXPANSIONCARDS_NETWORKING = {
  WIRELESS_NETWORK_ADAPTERS: "Wireless Network Adapters",
  SOUND_CARDS: "Sound Cards",
  WIRED_NETWORK_ADAPTERS: "Wired Network Adapters",
};

export const CATEGORY = {
  GENERAL: "General",
  PERIPHERALS: "Peripherals",
  ACCESSORIES_OTHER: "Accessories / Other",
  EXPANSIONCARDS_NETWORKING: "Expansion Cards / Networking",
};

export const SUB_CATEGORY = {
  VIDEO_CARDS: "Video Cards",
  CPUS: "CPUs",
  CPU_COOLERS: "CPU Coolers",
  OPTICAL_DRIVES: "Optical Drives",
  MEMORY: "Memory",
  MONITORS: "Monitors",
  INTERNAL_STORAGE: "Storage",
  CASES: "Cases",
  MOTHERBOARDS: "Motherboards",
  OPERATING_SYSTEMS: "Operating Systems",
  EXTERNAL_STORAGE: "External Storage",
  POWER_SUPPLIES: "Power Supplies",
  SPEAKERS: "Speakers",
  HEADPHONES: "Headphones",
  MICE: "Mice",
  WEBCAMS: "Webcams",
  KEYBOARDS: "Keyboards",
  FAN_CONTROLLERS: "Fan Controllers",
  CASE_ACCESSORIES: "Case Accessories",
  CASE_FANS: "Case Fans",
  THERMAL_COMPOUND: "Thermal Compound",
  UPS_SYSTEMS: "UPS Systems",
  WIRELESS_NETWORK_ADAPTERS: "Wireless Network Adapters",
  SOUND_CARDS: "Sound Cards",
  WIRED_NETWORK_ADAPTERS: "Wired Network Adapters",
};

export const SORT_BY = {
  NEW: "New",
  A_Z: "A - Z",
  Z_A: "Z - A",
  PRICE_LOW: "Price Low",
  PRICE_HIGH: "Price High",
  DISCOUNT_LOW: "Discount Low",
  DISCOUNT_HIGH: "Discount High",
};

const PRODUCT_FIELDS = {
  KEYBOARDS: {
    name: "Razer Huntsman Mini",
    price: 97.99,
    style: "Mini",
    switches: "Razer Red Optical Linear",
    backlit: "RGB",
    tenkeyless: true,
    connection_type: "Wired",
    color: "Black",
    category: "Peripherals",
    subcategory: "Keyboards",
  },
  MOTHERBOARDS: {
    name: "Gigabyte B650 AORUS ELITE AX",
    price: 199,
    socket: "AM5",
    form_factor: "ATX",
    max_memory: 192,
    memory_slots: 4,
    color: "Black / Silver",
    category: "General",
    subcategory: "Motherboards",
  },
  CPUS: {
    name: "AMD Ryzen 5 5600X",
    price: 157.86,
    core_count: 6,
    core_clock: 3.7,
    boost_clock: 4.6,
    tdp: 65,
    graphics: null,
    smt: true,
    category: "General",
    subcategory: "CPUs",
  },
  OPTICAL_DRIVES: {
    name: "LG WH14NS40",
    price: 69,
    bd: 12,
    dvd: 16,
    cd: 48,
    bd_write: "14/12/2/2",
    dvd_write: "16/8/8/16/6/8/5",
    cd_write: "48/24",
    category: "General",
    subcategory: "Optical Drives",
  },
  CASE_ACCESSORIES: {
    name: "Vantec UGT-CR935",
    price: 32.99,
    type: "Card Reader",
    form_factor: 3.5,
    category: "Accessories / Other",
    subcategory: "Case Accessories",
  },
  INTERNAL_STORAGE: {
    name: "Western Digital Black SN850X",
    price: 299.99,
    capacity: 4000,
    price_per_gb: 0.075,
    type: "SSD",
    cache: null,
    form_factor: "M.2-2280",
    interface: "M.2 PCIe 4.0 X4",
    category: "General",
    subcategory: "Storage",
  },
  VIDEO_CARDS: {
    name: "MSI GeForce RTX 3060 Ventus 2X 12G",
    price: 289.99,
    chipset: "GeForce RTX 3060 12GB",
    memory: 12,
    core_clock: 1320,
    boost_clock: 1777,
    color: "Black",
    length: 235,
    category: "General",
    subcategory: "Video Cards",
  },
  MONITORS: {
    name: "Dell UP3218K",
    price: 4024.99,
    screen_size: 31.5,
    resolution: [7680, 4320],
    refresh_rate: 60,
    response_time: 6,
    panel_type: "IPS",
    aspect_ratio: "16:9",
    category: "General",
    subcategory: "Monitors",
  },
  MEMORY: {
    name: "Corsair Vengeance RGB Pro 32 GB",
    price: 94.99,
    speed: [4, 3600],
    modules: [2, 16],
    price_per_gb: 2.968,
    color: "Black",
    first_word_latency: 10,
    cas_latency: 18,
    category: "General",
    subcategory: "Memory",
  },
  OPERATING_SYSTEMS: {
    name: "Microsoft Windows 11 Home (64-bit)",
    price: 117.98,
    mode: 64,
    max_memory: 128,
    category: "General",
    subcategory: "Operating Systems",
  },
  FAN_CONTROLLERS: {
    name: "Kingwin FPX-001",
    price: 15.99,
    channels: 4,
    channel_wattage: 8,
    pwm: false,
    form_factor: 3.5,
    color: null,
    category: "Accessories / Other",
    subcategory: "Fan Controllers",
  },
  CASES: {
    name: "Lian Li O11 Dynamic EVO",
    price: 149.99,
    type: "ATX Mid Tower",
    color: "White / Gray",
    psu: null,
    side_panel: "Tempered Glass",
    external_volume: null,
    internal_35_bays: 6,
    category: "General",
    subcategory: "Cases",
  },
  MICE: {
    name: "Logitech G502 HERO",
    price: 36.99,
    tracking_method: "Optical",
    connection_type: "Wired",
    max_dpi: 25600,
    hand_orientation: "Right",
    color: "Black",
    category: "Peripherals",
    subcategory: "Mice",
  },
  UPS_SYSTEMS: {
    name: "APC SURT20KRMXLT",
    price: 19850,
    capacity_w: 16000,
    capacity_va: 20000,
    category: "Accessories / Other",
    subcategory: "UPS Systems",
  },
  WEBCAMS: {
    name: "Razer Kiyo Pro Ultra",
    price: 299.99,
    resolutions: ["4k", "2k", "1080p", "720p"],
    connection: "USB 3.2 Gen 1 Type-A",
    focus_type: "Auto",
    os: ["Windows"],
    fov: 82,
    category: "Peripherals",
    subcategory: "Webcams",
  },
  WIRED_NETWORK_ADAPTERS: {
    name: "Intel E1G42ETBLK",
    price: 53,
    interface: "PCIe x4",
    color: null,
    category: "Expansion Cards / Networking",
    subcategory: "Wired Network Adapters",
  },
  WIRELESS_NETWORK_ADAPTERS: {
    name: "Asus PCE-AX3000",
    price: 39.99,
    protocol: "Wi-Fi 6",
    interface: "PCIe x1",
    color: "Black",
    category: "Expansion Cards / Networking",
    subcategory: "Wireless Network Adapters",
  },
  HEADPHONES: {
    name: "HiFiMAN Susvara",
    price: 5999,
    type: "Circumaural",
    frequency_response: [6, 75],
    microphone: false,
    wireless: false,
    enclosure_type: "Open",
    color: "Silver / Brown",
    category: "Peripherals",
    subcategory: "Headphones",
  },
  SPEAKERS: {
    name: "Logitech THX Z-5300e",
    price: null,
    configuration: 5.1,
    wattage: 280,
    frequency_response: [35, 20],
    color: null,
    category: "Peripherals",
    subcategory: "Speakers",
  },
  CASE_FANS: {
    name: "Noctua A12x25 PWM",
    price: 32.95,
    size: 120,
    color: "Brown",
    rpm: [450, 2000],
    airflow: [49.73, 60.1],
    noise_level: [18.8, 22.6],
    pwm: true,
    category: "Accessories / Other",
    subcategory: "Case Fans",
  },
};
